---
title: "Attempt 1"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(ggplot2)
library(tidyverse)
library(shinythemes)

```

Load Data
```{r}
load("../datFlow.Rda")
#datFlow$date = as.Date(datFlow$date)
```

Functions to get mnf and based on the night start and end time
```{r}
get_mnf = function(df, night_start, night_end){
  df = df %>% 
    filter((night_start <= tod) & (tod <= night_end)) %>% 
    group_by(id, date) %>% 
    summarise(mnf=min(y)) %>% 
    ungroup()
  return(df)
}

get_adf = function(df, night_start, night_end){
  df= df %>% 
    filter((night_start > tod) | (tod > night_end)) %>% 
    group_by(id, date) %>% 
    summarise(adf=mean(y)) %>% 
    ungroup()
  return(df)
}
```


### Compute 7 days rolling average for MNF
```{r}
inter_roll <- function(df, n_days=7){
  new <- df %>% 
    mutate(mnf_roll=rollmean(mnf, n_days, na.pad=TRUE)) %>% 
    select(-mnf)
  new$mnf_roll = na.spline(new$mnf_roll, 1:nrow(new))
  return(new)
}
```

Plot time series for one id
```{r}
myid = "AW008"
df = datFlow %>% 
  filter(id == myid) %>% 
  mutate(date = as.Date(date))
ggplot(df, aes(x = date, y = y))+
  geom_path()
```

Define UI
```{r}
ui = fluidPage(theme = shinytheme("lumen"),
               titlePanel("Time series for given meter ID"),
               sidebarLayout(
                 sidebarPanel(
                   # select meter id to be plotted
                   selectInput(inputId = "meter_id", 
                               label = strong("Meter Id"),
                               choices = unique(datFlow$id),
                               selected = "AW008"),
                   
                   dateRangeInput(inputId = "date",
                                  strong("Date range"),
                                  start = "2017-01-01",
                                  end = "2020-01-26",
                                  min = "2017-01-01",
                                  max = "2020-01-26")
                 ),
                 
                   # output
                   mainPanel(
                     plotOutput(outputId = "timeseries")
                   )
               )
)
```

Define Server function
```{r}
server = function(input, output) {
  # subset data using the input
  selected_series = reactive({
      # validate input data
    req(input$date)
    validate(need(!is.na(input$date[1]) & !is.na(input$date[2]), "Error: Please provide both a start and an end date."))
    validate(need(input$date[1] < input$date[2], "Error: Start date should be earlier than end date."))
    datFlow %>% 
      filter(
        id == input$meter_id,
        date > as.Date(input$date[1]) & date < as.Date(input$date[2])
      )
  })
  
  # create plot object that the plotOutput function is expecting
  output$timeseries = renderPlot({
    plot(x = as.Date(selected_series()$date), y = selected_series()$y, type = 'l')
  })
}

# create shiny object
shinyApp(ui = ui, server = server)
```
